// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParksLookup.Models;

namespace ParksLookup.Migrations
{
    [DbContext(typeof(ParksLookupContext))]
    partial class ParksLookupContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ParksLookup.Models.Park", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Type")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "Maine",
                            Name = "Acadia National Park",
                            Type = "National"
                        },
                        new
                        {
                            Id = 2,
                            Location = "Utah",
                            Name = "Arches National Park",
                            Type = "National"
                        },
                        new
                        {
                            Id = 3,
                            Location = "Colorado",
                            Name = "Eldorado Canyon State Park",
                            Type = "State"
                        },
                        new
                        {
                            Id = 4,
                            Location = "Colorado",
                            Name = "Lory State Park",
                            Type = "State"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
